### ISSUE TITLE
Commission

### ISSUE THREAD

**Issue by Temz75** [ewewukek/mc-musketmod#10]
Is it possible that you can make this musket mod again but for a 1.17.1 bukkit plugin for my server? I would like to commission your work if possible!

**Comment by ewewukek** [comment]
hi! this is a fabric/forge mod, bukkit plugins are a different thing. there are server versions that allow running bukkit plugins alongside with forge or fabric mods, you could use that and simply drop the mod to server. clients would also need to install the mod.
