### ISSUE TITLE
[Bug] ClassCastException on rendering PlayerEntity in 3rd Person

### ISSUE THREAD

**Issue by Cheaterpaul** [ewewukek/mc-musketmod#11]
## Versions
- Minecraft: 1.16.5
- Forge: 36.2.0
- musketmod-1.16.5-forge-1.4.1
- Werewolves: 1.8-0.5.6
- Vampirism: 1.8.4
---
For reference: https://github.com/TeamLapen/Werewolves/issues/65
I have gotten a crash-report from someone who uses this mod and my [werewolves](https://github.com/TeamLapen/Werewolves) mod together. This is caused because i render the player with a werewolf model instead of the player model, resulting in a ClassCastException here https://github.com/ewewukek/mc-musketmod/blob/d5f712a3907b0f769ea40d8b0b3602b6bae16f60/src/main/java/ewewukek/musketmod/ClientSetup.java#L55

While testing i noticed that the `RenderLivingEvent.Pre` does not care about the generic parameter (it is too costly for forge to fire generic aware events) thus every eventhandler receives events for all entities and all models. 

It may seem to be unnecessary for checking if the model is a PlayerModel if the entity is a player, but is it possible.

**Comment by ewewukek** [comment]
thanks for such detailed report) i'll add a necessary type check and review other places that may have similar assumptions

**Comment by ewewukek** [comment]
uploaded new release to curseforge. i believe the bug is fixed now)

**Comment by Cheaterpaul** [comment]
Thanks for the fast reply and fix :+1:
