### ISSUE TITLE
Musket melee crashes with Sodium

### ISSUE THREAD

**Issue by ejektaflex** [ewewukek/mc-musketmod#12]
Having Sodium installed results in a crash.

https://gist.github.com/ejektaflex/1da0b873b9b7fef6f3544184e82e5922

This looks like it could be a pretty trivial fix, since it has to do with a null arm pose. Thanks!

**Comment by ewewukek** [comment]
that's not Sodium's fault but entirely my slopiness)
fixed in latest release (1.4.3)

**Comment by ejektaflex** [comment]
Yes - that fixed it. Thanks!

**Comment by red2blue** [comment]
@ewewukek This crash happens when you open inventory, or open a patchouli book... with your latest update.

**Comment by ewewukek** [comment]
@red2blue you didn't tell which minecraft version you're getting crash on i presume it's 1.17.1. it also had that bug and is now fixed in 1.4.3 release

**Comment by red2blue** [comment]
1.18

**Comment by ewewukek** [comment]
i'll try to be play as detective and deduce that you're using fabric :P
also please create a new issue because OP's one is resolved. and add a crashlog - they help a lot in understanding what exactly went wrong
