### ISSUE TITLE
Game crash and exit when going to bed.

### ISSUE THREAD

**Issue by Cursedth** [ewewukek/mc-musketmod#13]
Not crafted any items from the mod.

Happens when going to bed, game saves and exits and throws an error.

Using:
Forge  38.0.14
OptiFine HD U H3 pre7

--Crash report--
[crash-2021-12-05_09.00.40-client.txt](https://github.com/ewewukek/mc-musketmod/files/7655471/crash-2021-12-05_09.00.40-client.txt)

--Mod list--
[modlist.txt](https://github.com/ewewukek/mc-musketmod/files/7655463/modlist.txt)

**Comment by ewewukek** [comment]
please update to 1.4.3 it has that bug fixed. i've moved all affected 1.4.2 files to archive so they don't show up in the files list
