### ISSUE TITLE
Bayonet musket scaling issue + proposition

### ISSUE THREAD

**Issue by Quartofel** [ewewukek/mc-musketmod#14]
As in the title, musket with bayonett is extremely small when shown as model (in my case when used with Back Slot mod, but that's also semi-issue in item frames etc.). I've noticed while snooping in the files and editing crafting recipes, that while musket and pistol are 16px textures while bayonet one is 32px which may be the cause of this minor inconvinience.

Now, to the proposition part - I'm hobbyist pixel "artist" and in the heat of the moment I re-did mod's sprites (in 16px, including the bayonet one). If you'd like them, I'd have no issue with you using them. Preview image below:
![image](https://user-images.githubusercontent.com/24753841/146487977-3841040b-06b3-46f4-84ca-9b6e81fd3157.png)

If you like them and you'd like to use them, let me know, I'll send you the .png's. Thanks for the mod!

PS Config option for reloading time would be _awesome_.

**Comment by ewewukek** [comment]
hi! i'll check why Back Slot mod displays bayonet incorrectly. it probably doesn't use scale value from the model. (i wanted bayonet to stick out from musket and using 32x32 textures with 2x scale was easiest way to achieve that)

i was thinking too about changing textures a little) i can put yours into a resource pack and add to the mod page if you wish.

P.S. i didn't make reloading time configurable because it would require modifying animations which is a real pain. but i will do it eventually)

**Comment by Quartofel** [comment]
Very nice! I'll try to post .png's for you here later today. 

Also, to clarify further, the "issue" I've got with model specifically with Back Slot is how it musket in comparison to size of pistol or even swords. It looks just so small!

**Comment by ewewukek** [comment]
i think i understand now what you mean by small) there is also another issue, musket with bayonet is positioned improperly
![musket](https://user-images.githubusercontent.com/18519775/146542768-3b7e4467-bfb5-41a2-b55c-b33ebbaff6e3.png)
![musket_with_bayonet](https://user-images.githubusercontent.com/18519775/146542775-5acdea2d-9f63-4272-96f3-1f853f625ed6.png)

that's probably is how Back Slot renders them. i'll dig into that mod when i have time

**Comment by raikasdev** [comment]
@Quartofel :wave: I was just wondering are your textures also CC0 like the other textures, because I would personally like to use them on my own vanilla server's muskets!
Thanks!

**Comment by ewewukek** [comment]
looks like new versions of BackSlot made adding compatibility a lot simpler
