### ISSUE TITLE
Strange hold animation using 3d blockbench musket

### ISSUE THREAD

**Issue by LedinecMing** [ewewukek/mc-musketmod#15]
![image](https://user-images.githubusercontent.com/63245550/153390879-42e35967-83f3-412b-b7ef-cafc09bc7f0f.png)

This happens when I have loaded musket

Model of loaded musket:
[musket_loaded.zip](https://github.com/ewewukek/mc-musketmod/files/8040328/musket_loaded.zip)

**Comment by ewewukek** [comment]
sorry for late response. I'm not good at modelling)

try downloading source code and importing existing model into Blockbench to edit. [src/main/resources/assets/musketmod/models/item/musket.json](https://github.com/ewewukek/mc-musketmod/blob/main/src/main/resources/assets/musketmod/models/item/musket.json)

also check existing models, maybe it will help [flintl0cks](https://www.curseforge.com/minecraft/texture-packs/flintl0cks)
