### ISSUE TITLE
I cannot get the 1.18.1 version in the CurseForge app

### ISSUE THREAD

**Issue by Moronblade** [ewewukek/mc-musketmod#16]
I cannot get the 1.18.1 version in the CurseForge app, but if another 1.18.1 mod (like Wandering Trapper) has your Musket mod as Required Dependency, i get the 1.17 version in the App.

**Comment by ewewukek** [comment]
can't say anything abour CurseForge app, never used it. mod now has 1.18.2 and 1.19.2 versions, i believe they are compatible with Wandering Trapper
