### ISSUE TITLE
Crash on Fabric

### ISSUE THREAD

**Issue by cezarymalek** [ewewukek/mc-musketmod#18]
Duuno what's the problem but looking on the log seem trivial (seems at least, tho we all know how it may look ;-) )
Anyway symptoms are simple as well... I get crash on the very start.
here's log:

[Text File.txt](https://github.com/ewewukek/mc-musketmod/files/9079528/Text.File.txt)

**Comment by ewewukek** [comment]
probably because i haven't updated the mod to 1.18.2 untill couple days ago. shouldn't happen now
