### ISSUE TITLE
Crash on 1.18.2

### ISSUE THREAD

**Issue by Catomax262** [ewewukek/mc-musketmod#19]
Error message spells: 
"Musket Mod (musketmod) has failed to load correctly"
" java.lang.NoClassDefFoundError: net/minecraft/tags/Tag$Named"

Log: https://mclo.gs/h8D5jAc

**Comment by ewewukek** [comment]
probably because i haven't updated the mod to 1.18.2 untill couple days ago. shouldn't happen now
