### ISSUE TITLE
[Suggestion] Add more cool stuff

### ISSUE THREAD

**Issue by Gixuu** [ewewukek/mc-musketmod#2]
List:
Dynamite: Must ignite it first with flint and steel to throw it and explode for a second.
Can be obtain from tnt block by extracting it. 
-------------------------------------------------------------
Smoke bomb: Receive invisibility for short period of time.
-------------------------------------------------------------
Bear trap: Mobs can't move if they get trapped for a while and receive slowness.
-------------------------------------------------------------

**Comment by ewewukek** [comment]
sorry, but this looks like a different mod to me. probably someone even did that already
