### ISSUE TITLE
Make guns being disguised code-side as crossbows/bows

### ISSUE THREAD

**Issue by TheSatanSpartan** [ewewukek/mc-musketmod#23]
Mods like Overloard and Guard Villagers are able to use crossbows and bows, 
can be a great integration to disguise the guns as crossbows or bows to make guns usable by those mods' mobs.

**Comment by TheSatanSpartan** [comment]
[---> Overlord Crossbow code](https://github.com/The-Fireplace-Minecraft-Mods/Overlord/blob/556bda18e6e6499599af21daf8a0359dd8782e01/common/src/main/java/dev/the_fireplace/overlord/entity/ai/goal/combat/AbstractArmyCrossbowAttackGoal.java#L42)

[ ---> Guard Villagers Crossbow code ](https://github.com/seymourimadeit/guardvillagers/blob/22f66e484c49bbdd79afc5237bde536c67a8db03/src/main/java/tallestegg/guardvillagers/entities/ai/goals/RangedCrossbowAttackPassiveGoal.java#L41)

**Comment by ewewukek** [comment]
Overlord appears to be stuck at 1.19.2

and it seems Guard Villagers supports guns already
