### ISSUE TITLE
[Suggestion] Shotgun/Blunderbuss & Piercing ammo

### ISSUE THREAD

**Issue by TANTRUM27X** [ewewukek/mc-musketmod#25]
I would ask if there is a plan to add a shotgun to this mod? I know you have antique shotgun mod but that mod is very different from this one.

Just adding a scatter ammo type would make reloading a pain. Having to move inventory around to load one gun with a single shot and the other with the scatter shot is not what you want to do in a tough fight. Being able to quickly reload each firearm individually from the hot bar, with no shuffling of items, would be ideal. So a firearm that only shoots scatter shot in the mod would be amazing!! It would be made simply like the others. (Which is where antique shotgun is kinda out of place) It would obviously have to be visually distinct from the musket to keep confusion down. A flared barrel like a blunderbuss?

All the normal configs would still make sense but might also add one for "Scatter range"(how wide the cone would be) and one for "pellet count"(how many projects are in said cone) perhaps.

 I would be fine with just having the paper cartridge work in it. However, I could understand the idea of making a separate 'scatter cartridge' that only works in the blunderbuss might make more sense.

That brings me to my next idea. Piercing ammo!? 
Either it goes the full range the firearm is set to in the config file (hitting all targets along the path) or a new config could be added to limit the piercing. (Only goes so far after hitting a target OR can only hit so many targets before it stops) Which ever is easier for you really would be cool imo.

I love this mod and will continue to use it. Yet, these two ideas would make it to where there is no chance of another mod outdoing it.

**Comment by duykhang3** [comment]
I made an addon which added a blunderbuss if you are still interested.

**Comment by Aryuken102** [comment]
> I made an addon which added a blunderbuss if you are still interested.

can you tell me the link or atleast the name i wanna try it :D

**Comment by ewewukek** [comment]
added blunderbuss item. uses same ammo for simplicity. not sure about piercing ammo, I'll put it in a list for now)
there are few more things I want to do before blunderbuss gets into new release
