### ISSUE TITLE
Crash wen shooting dummy

### ISSUE THREAD

**Issue by Aryuken102** [ewewukek/mc-musketmod#28]
idk what happend it just crashed when i shot dummmmy mod dummy
i have couple mod installed too just reminder

here the crash report

[crash-2024-03-10_21.15.13-server.txt](https://github.com/ewewukek/mc-musketmod/files/14550521/crash-2024-03-10_21.15.13-server.txt)

**Comment by ewewukek** [comment]
thank you for reporting! fixed it: https://legacy.curseforge.com/minecraft/mc-mods/ewewukeks-musket-mod/files/5172206
