### ISSUE TITLE
There is a virus there?

### ISSUE THREAD

**Issue by Aryuken102** [ewewukek/mc-musketmod#29]
I went to download the update but....

![image](https://github.com/ewewukek/mc-musketmod/assets/145695023/9f883a29-9dc4-4af8-9d23-90e3010fbbf9)

![image](https://github.com/ewewukek/mc-musketmod/assets/145695023/6a1c2b04-57e3-417b-951e-533e89527661)

**Comment by ewewukek** [comment]
i have no idea why it says that. curseforge checks every uploaded file for malware. try downloading the mod on another computer, copy to yours and scan again.

**Comment by Aryuken102** [comment]
> i have no idea why it says that. curseforge checks every uploaded file for malware. try downloading the mod on another computer, copy to yours and scan again.

i test downloading other mod to update it and the same issue comes up but i download older version everything is fine maybe i need to tell curse about this?

**Comment by ewewukek** [comment]
probably, this sounds like common issue for some players. maybe they can give advice on configuring your antivirus
