### ISSUE TITLE
Curseforge page is marked as being a Fabric mod?

### ISSUE THREAD

**Issue by Derpford** [ewewukek/mc-musketmod#3]
Apparently this mod is showing up as a Fabric mod on Curseforge, even though it does not appear to support Fabric right now. This can be observed by going to the Armor, Tools and Weapons tab in Curseforge, setting the "Version" drop-down to "Fabric", and clicking through until you find the mod (as of writing, it appears at the top of page 3).

I don't know how to fix this. I suspect there was an earlier version that supported Fabric at some point, which is marking the whole mod as supporting Fabric, even though current versions are only for Forge. Maybe this is a glitch on Curseforge's end. Goodness knows Curseforge is doing a poor job of helping people filter mods by what modloader they support...

**Comment by ewewukek** [comment]
yep, there was an older version incorrectly marked as supporting Fabric. thanks for the report)
