### ISSUE TITLE
Modrinth Upload

### ISSUE THREAD

**Issue by begrs** [ewewukek/mc-musketmod#31]
Could you be so kind and upload you mod to **Modrinth** too?
For me the Fabric version would be enough.

I would really like to use it in my mod(+modpack) and would love to give you more downloads :)
(I have another friend who made their pack on modrinth and would like to use it as well.)

(For the record and because I was asked: I know the MIT license would allow me to upload it there myself, but that would feel dirty and rob the author of all monetary benefits. So to all others apart from the author, please don't upload it just to fulfill my issue, unless there is no reply for more than two months.)

**Comment by ewewukek** [comment]
so I decided to publish all my mods on modrinth)
https://modrinth.com/mod/ewewukeks-musket-mod

**Comment by begrs** [comment]
@ewewukek thank you so much :)
