### ISSUE TITLE
Request module interaction

### ISSUE THREAD

**Issue by whydm2003724** [ewewukek/mc-musketmod#32]
The module I am requesting interaction with is (Guard Villagers).
The firearms in your mod are relatively similar to the original style, and the mechanism doesn't look complicated, so it should be relatively balanced.
This is really great!
And now in the hands of these villagers, it can only be used for close combat
Imagine how cool it would be when the gun in the guard's hand rings!

**Comment by whydm2003724** [comment]
Of course, I also hope that both Forge and Fabric can experience this excellent interaction whenever feasible.

**Comment by whydm2003724** [comment]
Of course, I also hope that both Forge and Fabric can experience this excellent interaction whenever feasible.

**Comment by ewewukek** [comment]
I checked Guard Villagers code, it looks like that mod already supports guns. or maybe that feature is being worked on.
I'll simply make sure I don't break that
