### ISSUE TITLE
[Enhancement] Make musket's bullet ignite TNT

### ISSUE THREAD

**Issue by MinecraftGuy926** [ewewukek/mc-musketmod#33]
Would be pretty cool. Sorta like flaming arrows do

**Comment by MinecraftGuy926** [comment]
has this be officially release yet? hoping for a fabric 1.20.1 version

**Comment by ewewukek** [comment]
uploaded new version for 1.20.1

I'll also port new features from 1.21 to 1.20.1 once finished

**Comment by MinecraftGuy926** [comment]
Thank you so much!! :D
