### ISSUE TITLE
Breakable Glass with Config Options

### ISSUE THREAD

**Issue by mxnmnm** [ewewukek/mc-musketmod#36]
### Minecraft Version

1.20.1+

### Request information

Can we get the option for muskets to shoot through and break glass? It feels kinda weird that glass panes and cobblestone equally protect against bullets. Maybe a config option of what blocks bullets can pass through and one for what blocks bullets can break? Maybe the option of adding in items tags as well as items for better mod compat and an easier time adding blocks to configs?

**Comment by ewewukek** [comment]
i'll add block breaking (destroy or drop options). not sure about shooting through, hit detection is already too complicated with all liquid detection mechanics)

**Comment by ewewukek** [comment]
added two tags, one for destroying blocks, another to drop them as items
