### ISSUE TITLE
Third Person animation Compatibility 

### ISSUE THREAD

**Issue by DuskCrow19** [ewewukek/mc-musketmod#37]
### Minecraft Version

1.20.1

### ModLoader

Forge

### Request information

So im using the Real Camera mod, but when reloading and aiming during the first person view the weapons are looking down, you can shoot to the way you are aiming but the gun doest look in that direction, while in 3rd person the gun looks like it should be. 
![m2](https://github.com/user-attachments/assets/ae4d1ddd-3ded-4654-a970-1c7c7f731453)
![m1](https://github.com/user-attachments/assets/a755e6fb-921f-4e3e-a9f5-8093929f30d1)

**Comment by ewewukek** [comment]
it works properly on NeoForge 1.21
i'll see if the bug can be fixed on my side for 1.20.1 or forward it to Real Camera author

**Comment by DuskCrow19** [comment]
thank you, i love your mod by the way

**Comment by ewewukek** [comment]
I noticed that pistols look ugly with Real Camera, so I redone that part. which also happens to fix this bug)
