### ISSUE TITLE
Conflict with Better Nether

### ISSUE THREAD

**Issue by NECOBLADE** [ewewukek/mc-musketmod#40]
### Minecraft Version

1.20.1

### ModLoader

Fabric

### Musket Mod version

musketmod-1.20.1-fabric-1.5.1.

### Modpack info or mod list(please reduce mod range)

  [✔] bclib-3.0.14   [✔] better-nether-9.0.10   [✔] cloth-config-11.1.118-fabric   [✔] musketmod-1.20.1-fabric-1.5.1   [✔] qfapi-7.6.0_qsl-6.2.0_fapi-0.92.2_mc-1.20.1

### The latest.log file and hs_err_pidXXX if exists

https://pastebin.com/Nqg4zWNQ

### Issue description

Game crashes on load when running musketmod-1.20.1-fabric-1.5.1 and better-nether-9.0.10. on Minecraft 1.20.1 .

### Steps to reproduce

1:Install the mention mod versions.
2:Run game.
3:Crash.

**Comment by ewewukek** [comment]
are you running Quilt loader? I tested it with Fabric loader and everything seems fine. and qfapi is ignored because it's not a Fabric mod

**Comment by NECOBLADE** [comment]
I am, yes. Is there a way that I could fix it on my end?

**Comment by ewewukek** [comment]
no, I'll need to rewrite my mixins in a more compatible way. I'll post a test build once I'm done since I don't have Quilt installed)

**Comment by NECOBLADE** [comment]
Alrighty. I'll be sure to check it out when you post. Thank you for your hard work. I put this mod in every single modpack I make.

**Comment by ewewukek** [comment]
I changed most mixins including one causing issues with Quilt. only one left to fix.
see if this build fixes game launch. at worst the error message should change)
[test.zip](https://github.com/user-attachments/files/16788279/test.zip)

**Comment by NECOBLADE** [comment]
Everything seems to work. Thank you for fixing this so quickly!

**Comment by ewewukek** [comment]
that's great) I'll roll a new release after fixing last mixin and testing everything again
