### ISSUE TITLE
Incompatible with Iron's Spells 'n Spellbooks

### ISSUE THREAD

**Issue by Juan-the-magnificent** [ewewukek/mc-musketmod#41]
### Minecraft Version

1.20.1

### ModLoader

Forge

### Musket Mod version

1.5.1

### Modpack info or mod list(please reduce mod range)

https://gist.github.com/Juan-the-magnificent/9bcacbe17e117cdafdf94aacf7c5b04e

### The latest.log file and hs_err_pidXXX if exists

https://gist.github.com/Juan-the-magnificent/9bcacbe17e117cdafdf94aacf7c5b04e

### Issue description

Crashes on startup

### Steps to reproduce

1. launch Minecraft with mods 2. crash

**Comment by ewewukek** [comment]
fixed in 1.5.2
