### ISSUE TITLE
Unloaded musket arm position

### ISSUE THREAD

**Issue by MinecraftGuy926** [ewewukek/mc-musketmod#42]
### Minecraft Version

1.20.1

### ModLoader

Fabric

### Request information

In 1.5.2 the unloaded musket is held the same way as the loaded musket 
![image](https://github.com/user-attachments/assets/fadf2804-34aa-4428-ad1a-943e5a5834b0)

while the unloaded musket in the offhand is at ease
![image](https://github.com/user-attachments/assets/fdf38e36-7fed-4a81-9aaf-298f8df5b1ee)

I'm trying to update the 3D models resource pack. But with this new position change, I can no longer have the unloaded gun in this position which I'm very fond of ![image](https://github.com/user-attachments/assets/38bf82a1-4005-484b-b60e-c3f816ac7792)

Perhaps you could revert this change and let the unloaded musket be held like it used to be? Thanks

**Comment by ewewukek** [comment]
it really looks nice) I'll add a predicate for relaxed state that will trigger couple seconds after firing

**Comment by MinecraftGuy926** [comment]
awesome thank you

**Comment by MinecraftGuy926** [comment]
demo of the difference between 1.4.9 and 1.5.2
https://github.com/user-attachments/assets/66d76ac1-61c8-4c4a-8618-b51fb71f306f

**Comment by ewewukek** [comment]
I'll make the delay configurable. instantly dropping arms felt wrong with Real Camera mod so I made it always aim so it looks like in first person view

**Comment by ewewukek** [comment]
made aiming optional. and added new model predicates to allow positioning guns during animations.
so now there are 6 model variants for each gun:
- base model and `_loaded` variant for idle pose
- `_loading` and `_loading_loaded` for loading animation. (inherit first two and only change position)
- `_aiming` and `_aiming_loaded` for aiming pose. (also inherit first two and change position)

example: [musket.json](https://github.com/ewewukek/mc-musketmod/blob/main/src/main/resources/assets/musketmod/models/item/musket.json#L255)

**Comment by MinecraftGuy926** [comment]
Incredible! You went above and beyond.
Thank you
