### ISSUE TITLE
Team Damage

### ISSUE THREAD

**Issue by talhanation** [ewewukek/mc-musketmod#43]
### Request information

add friendly fire support, by adding this line to onHitEntityMethod(Hitresult)

Entity hitEntity = hitResult.getEntity();
Entity ownerEntity = this.getOwner();

if(ownerEntity.getTeam() != null && ownerEntity.getTeam().isAlliedTo(hitEntity.getTeam()) && !ownerEntity.getTeam().isAllowFriendlyFire()) return;

**Comment by talhanation** [comment]
*to be compatible with recruits mod as the entities are not players

**Comment by ewewukek** [comment]
sure, that looks reasonable

**Comment by ewewukek** [comment]
done.
I also added `mobReload` helper method to complement `mobUse` and `aimAt` that hopefully should make integrating guns in other mods easier. `RangedGunAttackGoal` can serve as example
