### ISSUE TITLE
Conflict with red cap in twilight forest

### ISSUE THREAD

**Issue by AQUAMEinGithub** [ewewukek/mc-musketmod#46]
### Minecraft version

1.20.1

### Mod loader you are using

Forge

### Musket Mod version

musketmod-1.20.1-forge-1.5.2.jar

### Modpack info or mod list

Mod List: 
		totw_modded-forge-1.20.1-1.0.5.jar                |Towers of the Wild Modded     |totw_modded                   |1.0.5               |DONE      |Manifest: NOSIGNATURE
		man_of_many_planes-0.2.0+1.20.1-forge.jar         |Man of Many Planes            |man_of_many_planes            |0.2.0+1.20.1        |DONE      |Manifest: NOSIGNATURE
		kuma-api-forge-20.1.8+1.20.1.jar                  |KumaAPI                       |kuma_api                      |20.1.8              |DONE      |Manifest: NOSIGNATURE
		Stackable Potions-forge-1.20.1-1.0.0.jar          |Stackable Potions             |stackablepotions              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		EasyAnvils-v8.0.2-1.20.1-Forge.jar                |Easy Anvils                   |easyanvils                    |8.0.2               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		geckolib-forge-1.20.1-4.4.7.jar                   |GeckoLib 4                    |geckolib                      |4.4.7               |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2-rc1+1.20.jar     |Player Animator               |playeranimator                |1.0.2-rc1+1.20      |DONE      |Manifest: NOSIGNATURE
		immersive_aircraft-1.1.2+1.20.1-forge.jar         |Immersive Aircraft            |immersive_aircraft            |1.1.2+1.20.1        |DONE      |Manifest: NOSIGNATURE
		aquaculture_delight_1.0.0_forge_1.20.1.jar        |Aquaculture Delight           |aquaculturedelight            |1.0.0               |DONE      |Manifest: NOSIGNATURE
		sophisticatedcore-1.20.1-0.6.22.611.jar           |Sophisticated Core            |sophisticatedcore             |0.6.22.611          |DONE      |Manifest: NOSIGNATURE
		create_jetpack-forge-4.2.1-bugfix1.jar            |Create Jetpack                |create_jetpack                |4.2.1-bugfix1       |DONE      |Manifest: NOSIGNATURE
		Placebo-1.20.1-8.6.2.jar                          |Placebo                       |placebo                       |8.6.2               |DONE      |Manifest: NOSIGNATURE
		citadel-2.5.6-1.20.1.jar                          |Citadel                       |citadel                       |2.5.6               |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.20-Forge-4.0.5.jar                     |YUNG's API                    |yungsapi                      |1.20-Forge-4.0.5    |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0.jar                       |MixinExtras                   |mixinextras                   |0.2.0               |DONE      |Manifest: NOSIGNATURE
		musketmod-1.20.1-forge-1.5.2.jar                  |Musket Mod                    |musketmod                     |1.5.2               |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.20.1-3.20.5.1044.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |3.20.5.1044         |DONE      |Manifest: NOSIGNATURE
		littlecontraptions-forge-1.20.1.2.jar             |Little Contraptions           |littlecontraptions            |1.20.1.2            |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.20.1-1.6.6.jar                   |Guard Villagers               |guardvillagers                |1.20.1-1.6.6        |DONE      |Manifest: NOSIGNATURE
		create_dragon_lib-1.20.1-1.4.3.jar                |Create: Dragon Lib            |create_dragon_lib             |1.4.3               |DONE      |Manifest: NOSIGNATURE
		createdieselgenerators-1.20.1-1.2i.jar            |Create Diesel Generators      |createdieselgenerators        |1.20.1-1.2i         |DONE      |Manifest: NOSIGNATURE
		jeed-1.20-2.2.2.jar                               |Just Enough Effects Descriptio|jeed                          |1.20-2.2.2          |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.3.6-all.jar                   |Balm                          |balm                          |7.3.6               |DONE      |Manifest: NOSIGNATURE
		FpsReducer2-forge-1.20-2.5.jar                    |FPS Reducer                   |fpsreducer                    |1.20-2.5            |DONE      |Manifest: NOSIGNATURE
		YungsBetterNetherFortresses-1.20-Forge-2.0.6.jar  |YUNG's Better Nether Fortresse|betterfortresses              |1.20-Forge-2.0.6    |DONE      |Manifest: NOSIGNATURE
		dragonfight-1.20.1-4.6.jar                        |dragonfight mod               |dragonfight                   |1.20.1-4.6          |DONE      |Manifest: NOSIGNATURE
		cloth-config-11.1.118-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.118            |DONE      |Manifest: NOSIGNATURE
		dummmmmmy-1.20-1.8.19.jar                         |MmmMmmMmmmmm                  |dummmmmmy                     |1.20-1.8.19         |DONE      |Manifest: NOSIGNATURE
		AutoLeveling-1.20-1.19b.jar                       |Auto Leveling                 |autoleveling                  |1.19b               |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.20.1-4.3.2508-universal.jar      |The Twilight Forest           |twilightforest                |4.3.2508            |DONE      |Manifest: NOSIGNATURE
		sodiumdynamiclights-forge-1.0.8-1.20.1.jar        |Sodium Dynamic Lights         |sodiumdynamiclights           |1.0.8               |DONE      |Manifest: NOSIGNATURE
		embeddium-0.3.31+mc1.20.1.jar                     |Embeddium                     |embeddium                     |0.3.31+mc1.20.1     |DONE      |Manifest: NOSIGNATURE
		embeddiumplus-1.20.1-v1.2.13.jar                  |Embeddium++                   |embeddiumplus                 |1.2.13              |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.20.1-2.16.2.jar                   |Structure Gel API             |structure_gel                 |2.16.2              |DONE      |Manifest: NOSIGNATURE
		corpse-forge-1.20.1-1.0.12.jar                    |Corpse                        |corpse                        |1.20.1-1.0.12       |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.20.1-1.2.4.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.4        |DONE      |Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v6.1.1_mc1.20.1.jar           |AmbientSounds                 |ambientsounds                 |6.1.1               |DONE      |Manifest: NOSIGNATURE
		projectvibrantjourneys-1.20.1-6.0.0.jar           |Project: Vibrant Journeys     |projectvibrantjourneys        |1.20.1-6.0.0        |DONE      |Manifest: NOSIGNATURE
		valhelsia_structures-forge-1.20.1-1.1.2.jar       |Valhelsia Structures          |valhelsia_structures          |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		sleep_tight-1.20-1.1.19.jar                       |Sleep Tight                   |sleep_tight                   |1.20-1.1.19         |DONE      |Manifest: NOSIGNATURE
		YungsBridges-1.20-Forge-4.0.3.jar                 |YUNG's Bridges                |yungsbridges                  |1.20-Forge-4.0.3    |DONE      |Manifest: NOSIGNATURE
		dungeons_enhanced-1.20.1-5.2.2.jar                |Dungeons Enhanced             |dungeons_enhanced             |5.2.2               |DONE      |Manifest: NOSIGNATURE
		SnowWaifu-Forge-1.20.1-1.0.0.jar                  |SnowWaifu                     |snowwaifu                     |1.0.0               |DONE      |Manifest: NOSIGNATURE
		touhoulittlemaid-1.20.1-release-1.1.12-hotfix2.jar|Touhou Little Maid            |touhou_little_maid            |1.1.12-hotfix2      |DONE      |Manifest: NOSIGNATURE
		sisser-1.10.jar                                   |Sisser                        |sisser                        |1.10                |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.20.1-84-FORGE.jar                     |Patchouli                     |patchouli                     |1.20.1-84-FORGE     |DONE      |Manifest: NOSIGNATURE
		blockui-1.20.1-1.0.186-beta.jar                   |UI Library Mod                |blockui                       |1.20.1-1.0.186-beta |DONE      |Manifest: NOSIGNATURE
		oculus-mc1.20.1-1.7.0.jar                         |Oculus                        |oculus                        |1.7.0               |DONE      |Manifest: NOSIGNATURE
		CerbonsAPI-Forge-1.20.1-1.1.0.jar                 |Cerbons API                   |cerbons_api                   |1.1.0               |DONE      |Manifest: NOSIGNATURE
		YungsExtras-1.20-Forge-4.0.3.jar                  |YUNG's Extras                 |yungsextras                   |1.20-Forge-4.0.3    |DONE      |Manifest: NOSIGNATURE
		legendarysurvivaloverhaul-1.20.1-1.4.2.jar        |Legendary Survival Overhaul   |legendarysurvivaloverhaul     |1.20.1-1.20.1-1.4.2 |DONE      |Manifest: NOSIGNATURE
		curios-forge-5.9.1+1.20.1.jar                     |Curios API                    |curios                        |5.9.1+1.20.1        |DONE      |Manifest: NOSIGNATURE
		EnigmaticLegacy-2.30.1.jar                        |Enigmatic Legacy              |enigmaticlegacy               |2.30.1              |DONE      |Manifest: NOSIGNATURE
		littlelogistics-mc1.20.1-v1.20.1.2.jar            |Little Logistics              |littlelogistics               |1.20.1.2            |DONE      |Manifest: NOSIGNATURE
		architectury-9.2.14-forge.jar                     |Architectury                  |architectury                  |9.2.14              |DONE      |Manifest: NOSIGNATURE
		cupboard-1.20.1-2.7.jar                           |Cupboard utilities            |cupboard                      |1.20.1-2.7          |DONE      |Manifest: NOSIGNATURE
		YungsBetterEndIsland-1.20-Forge-2.0.6.jar         |YUNG's Better End Island      |betterendisland               |1.20-Forge-2.0.6    |DONE      |Manifest: NOSIGNATURE
		flightlib-forge-2.1.0.jar                         |Flight Lib                    |flightlib                     |2.1.0               |DONE      |Manifest: NOSIGNATURE
		FallingTree-1.20.1-4.3.4.jar                      |FallingTree                   |fallingtree                   |4.3.4               |DONE      |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		l2library-2.4.11-slim.jar                         |L2 Library                    |l2library                     |2.4.11              |DONE      |Manifest: NOSIGNATURE
		mobtimizations-forge-1.20.1-1.0.0.jar             |Mobtimizations                |mobtimizations                |1.20.1-1.0.0        |DONE      |Manifest: NOSIGNATURE
		YungsBetterMineshafts-1.20-Forge-4.0.4.jar        |YUNG's Better Mineshafts      |bettermineshafts              |1.20-Forge-4.0.4    |DONE      |Manifest: NOSIGNATURE
		veinmining-forge-1.5.0+1.20.1.jar                 |Vein Mining                   |veinmining                    |1.5.0+1.20.1        |DONE      |Manifest: NOSIGNATURE
		elytraslot-forge-6.4.3+1.20.1.jar                 |Elytra Slot                   |elytraslot                    |6.4.3+1.20.1        |DONE      |Manifest: NOSIGNATURE
		Kiwi-1.20.1-Forge-11.8.20.jar                     |Kiwi Library                  |kiwi                          |11.8.20+forge       |DONE      |Manifest: NOSIGNATURE
		fdcookbook-1.20.1-forge-1.6.1-rel.jar             |Farmer's Delight CookBook Refo|fdcookbook                    |1.6.1-rel           |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.10.0.40.jar                   |Just Enough Items             |jei                           |15.10.0.40          |DONE      |Manifest: NOSIGNATURE
		UniversalBoneMeal-v8.0.1-1.20.1-Forge.jar         |Universal Bone Meal           |universalbonemeal             |8.0.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		AttributeFix-Forge-1.20.1-21.0.4.jar              |AttributeFix                  |attributefix                  |21.0.4              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		the-conjurer-1.20.1-1.1.6.jar                     |The Conjurer                  |conjurer_illager              |1.1.6               |DONE      |Manifest: NOSIGNATURE
		callablehorses-1.20.1-1.3.0.1.jar                 |Callable Horses               |callablehorses                |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		map_atlases-1.20-6.0.9.jar                        |Map Atlases                   |map_atlases                   |1.20-6.0.9          |DONE      |Manifest: NOSIGNATURE
		caelus-forge-3.2.0+1.20.1.jar                     |Caelus API                    |caelus                        |3.2.0+1.20.1        |DONE      |Manifest: NOSIGNATURE
		Paxi-1.20-Forge-4.0.jar                           |Paxi                          |paxi                          |1.20-Forge-4.0      |DONE      |Manifest: NOSIGNATURE
		InvMove-1.20-0.8.4-Forge.jar                      |InvMove                       |invmove                       |0.8.4               |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.20-14.1.4.jar                   |Waystones                     |waystones                     |14.1.4              |DONE      |Manifest: NOSIGNATURE
		PassableFoliage-1.20.1-forge-8.2.1.jar            |Passable Foliage              |passablefoliage               |8.2.1               |DONE      |Manifest: NOSIGNATURE
		FastSuite-1.20.1-5.0.1.jar                        |Fast Suite                    |fastsuite                     |5.0.1               |DONE      |Manifest: NOSIGNATURE
		integrated_api-1.5.1+1.20.1-forge.jar             |Integrated API                |integrated_api                |1.5.1+1.20.1-forge  |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.20.1-1.11.2-forge.jar            |Nature's Compass              |naturescompass                |1.20.1-1.11.2-forge |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.20.1-9.0.0.46.jar                 |Serene Seasons                |sereneseasons                 |9.0.0.46            |DONE      |Manifest: NOSIGNATURE
		sereneseasonfix-1.20.1-1.0.8.jar                  |Sereneseasonfix               |sereneseasonfix               |1.20.1-1.0.8        |DONE      |Manifest: NOSIGNATURE
		HQM-1.20.1-5.16.0-forge.jar                       |Hardcore Questing Mode        |hardcorequesting              |1.20.1-5.16.0       |DONE      |Manifest: NOSIGNATURE
		create-confectionery1.20.1_v1.1.0.jar             |Create Confectionery          |create_confectionery          |1.1.0               |DONE      |Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.20-Forge-3.0.3.jar     |YUNG's Better Desert Temples  |betterdeserttemples           |1.20-Forge-3.0.3    |DONE      |Manifest: NOSIGNATURE
		create_easy_structures-0.1.1-1.20.1.jar           |Create: Easy Structures       |create_easy_structures        |0.1.1               |DONE      |Manifest: NOSIGNATURE
		iceandfire-2.1.13-1.20.1-beta-5.jar               |Ice and Fire                  |iceandfire                    |2.1.13-1.20.1       |DONE      |Manifest: NOSIGNATURE
		BOMD-Forge-1.20.1-1.1.2.jar                       |Bosses of Mass Destruction    |bosses_of_mass_destruction    |1.1.2               |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-forge-1.20.1-14.0.43.jar             |CraftTweaker                  |crafttweaker                  |14.0.43             |DONE      |Manifest: NOSIGNATURE
		watut-forge-1.20.1-1.1.3.jar                      |What Are They Up To           |watut                         |1.20.1-1.1.3        |DONE      |Manifest: NOSIGNATURE
		puzzlesaccessapi-forge-8.0.7.jar                  |Puzzles Access Api            |puzzlesaccessapi              |8.0.7               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		DungeonsAriseSevenSeas-1.20.x-1.0.2-forge.jar     |When Dungeons Arise: Seven Sea|dungeons_arise_seven_seas     |1.0.2               |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.3.5-universal.jar                 |Forge                         |forge                         |47.3.5              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		TravelersTitles-1.20-Forge-4.0.2.jar              |Traveler's Titles             |travelerstitles               |1.20-Forge-4.0.2    |DONE      |Manifest: NOSIGNATURE
		untitledduckmod-0.7.0-forge-1.20.1.jar            |Untitled Duck Mod             |untitledduckmod               |0.7.0               |DONE      |Manifest: NOSIGNATURE
		tectonic-forge-1.20.1-2.4.1.jar                   |Tectonic                      |tectonic                      |2.4.1               |DONE      |Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		eidolon_repraised-1.20.1-0.3.8.13.jar             |Eidolon:Repraised             |eidolon                       |1.20.1-0.3.8.13     |DONE      |Manifest: NOSIGNATURE
		cofh_core-1.20.1-11.0.2.56.jar                    |CoFH Core                     |cofh_core                     |11.0.2              |DONE      |Manifest: NOSIGNATURE
		ensorcellation-1.20.1-5.0.2.24.jar                |Ensorcellation                |ensorcellation                |5.0.2               |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.20.1-3.0.1.6.jar             |TerraBlender                  |terrablender                  |3.0.1.6             |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.20.1-18.0.0.598.jar               |Biomes O' Plenty              |biomesoplenty                 |18.0.0.598          |DONE      |Manifest: NOSIGNATURE
		moonlight-1.20-2.12.9-forge.jar                   |Moonlight Library             |moonlight                     |1.20-2.12.9         |DONE      |Manifest: NOSIGNATURE
		Companion-1.20.1-Forge-5.2.0.jar                  |Companion                     |companion                     |5.2.0+forge         |DONE      |Manifest: NOSIGNATURE
		eyesoficeandfire-1.1.0-1.20.1.jar                 |Eyes of Ice and Fire          |eyesoficeandfire              |1.1.0-1.20.1        |DONE      |Manifest: NOSIGNATURE
		mixinsquared-forge-0.1.2-beta.6.jar               |MixinSquared                  |mixinsquared                  |0.1.2-beta.6        |DONE      |Manifest: NOSIGNATURE
		visual_keybinder-1.20.1 - 0.1.5.jar               |Raw's Visual Keybinder        |visual_keybinder              |1.20.1 - 0.1.5      |DONE      |Manifest: NOSIGNATURE
		trulytreasures-1.20-3.0.0-forge.jar               |Truly Treasures               |trulytreasures                |1.20-3.0.0          |DONE      |Manifest: NOSIGNATURE
		Jade-1.20.1-forge-11.9.3.jar                      |Jade                          |jade                          |11.9.3+forge        |DONE      |Manifest: NOSIGNATURE
		ShoulderSurfing-Forge-1.20.1-4.4.1.jar            |Shoulder Surfing Reloaded     |shouldersurfing               |1.20.1-4.4.1        |DONE      |Manifest: NOSIGNATURE
		another_furniture-forge-1.20.1-3.0.1.jar          |Another Furniture             |another_furniture             |1.20.1-3.0.1        |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.12.15_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.12.15             |DONE      |Manifest: NOSIGNATURE
		grindenc-forge-1.20.x-v2.1.jar                    |Grindstone Enchantments       |grindenc                      |2.1                 |DONE      |Manifest: NOSIGNATURE
		cleanswing-1.20-1.5.jar                           |Clean Swing Through Grass     |cleanswing                    |1.20-1.5            |DONE      |Manifest: NOSIGNATURE
		spectrelib-forge-0.13.15+1.20.1.jar               |SpectreLib                    |spectrelib                    |0.13.15+1.20.1      |DONE      |Manifest: NOSIGNATURE
		domum_ornamentum-1.20.1-1.0.203-beta-universal.jar|Domum Ornamentum              |domum_ornamentum              |1.20.1-1.0.203-beta |DONE      |Manifest: NOSIGNATURE
		astikorcarts-1.20.1-1.1.8.jar                     |AstikorCarts Redux            |astikorcarts                  |1.1.8               |DONE      |Manifest: NOSIGNATURE
		kffmod-4.10.0.jar                                 |Kotlin For Forge              |kotlinforforge                |4.10.0              |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.20.1-0.6.11-13.jar               |Flywheel                      |flywheel                      |0.6.11-13           |DONE      |Manifest: NOSIGNATURE
		oculus-flywheel-compat-forge1.20.1+1.1.2.jar      |Oculus Flywheel Compat        |irisflw                       |1.1.2               |DONE      |Manifest: NOSIGNATURE
		create-1.20.1-0.5.1.h.jar                         |Create                        |create                        |0.5.1.h             |DONE      |Manifest: NOSIGNATURE
		create_central_kitchen-1.20.1-for-create-0.5.1.f-1|Create: Central Kitchen       |create_central_kitchen        |1.3.12              |DONE      |Manifest: NOSIGNATURE
		integrated_stronghold-1.1.1+1.20.1-forge.jar      |Integrated Stronghold         |integrated_stronghold         |1.1.1+1.20.1-forge  |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-0.49.5+1.20.1.jar                 |Polymorph                     |polymorph                     |0.49.5+1.20.1       |DONE      |Manifest: NOSIGNATURE
		Zeta-1.0-24.jar                                   |Zeta                          |zeta                          |1.0-24              |DONE      |Manifest: NOSIGNATURE
		Quark-4.0-460.jar                                 |Quark                         |quark                         |4.0-460             |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.20-2.8.17.jar                   |Supplementaries               |supplementaries               |1.20-2.8.17         |DONE      |Manifest: NOSIGNATURE
		irons_spellbooks-1.20.1-3.4.0.1.jar               |Iron's Spells 'n Spellbooks   |irons_spellbooks              |1.20.1-3.4.0.1      |DONE      |Manifest: NOSIGNATURE
		jecharacters-1.20.1-forge-4.5.11.jar              |Just Enough Characters        |jecharacters                  |4.5.11              |DONE      |Manifest: NOSIGNATURE
		structurize-1.20.1-1.0.755-beta.jar               |Structurize                   |structurize                   |1.20.1-1.0.755-beta |DONE      |Manifest: NOSIGNATURE
		multipiston-1.20-1.2.43-RELEASE.jar               |Multi-Piston                  |multipiston                   |1.20-1.2.43-RELEASE |DONE      |Manifest: NOSIGNATURE
		coroutil-forge-1.20.1-1.3.7.jar                   |CoroUtil                      |coroutil                      |1.20.1-1.3.7        |DONE      |Manifest: NOSIGNATURE
		minecolonies-1.20.1-1.1.673-snapshot-universal.jar|MineColonies                  |minecolonies                  |1.20.1-1.1.673-snaps|DONE      |Manifest: NOSIGNATURE
		MineColonies_Tweaks-1.20.1-2.36.jar               |Tweaks addon for MineColonies |minecolonies_tweaks           |2.36                |DONE      |Manifest: NOSIGNATURE
		MineColonies_Compatibility-1.20.1-2.42.jar        |Compatibility addon for MineCo|minecolonies_compatibility    |2.42                |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.20.1-2.5.1.jar                |AppleSkin                     |appleskin                     |2.5.1+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		solcarrot-1.20.1-1.15.0.jar                       |Spice of Life: Carrot Edition |solcarrot                     |1.15.0              |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v8.1.21-1.20.1-Forge.jar               |Puzzles Lib                   |puzzleslib                    |8.1.21              |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		create_power_loader-1.5.0-mc1.20.1.jar            |Create: Power Loader          |create_power_loader           |1.5.0-mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.20.1-2.5.2.jar                      |Aquaculture 2                 |aquaculture                   |2.5.2               |DONE      |Manifest: NOSIGNATURE
		immersive_melodies-0.3.0+1.20.1-forge.jar         |Immersive Melodies            |immersive_melodies            |0.3.0+1.20.1        |DONE      |Manifest: NOSIGNATURE
		packetfixer-forge-1.4.2-1.19-to-1.20.1.jar        |Packet Fixer                  |packetfixer                   |1.4.2               |DONE      |Manifest: NOSIGNATURE
		trainperspectivefix-1.0.0-universal.jar           |Create: Train Perspective Fix |trainperspectivefix           |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		valhelsia_core-forge-1.20.1-1.1.2.jar             |Valhelsia Core                |valhelsia_core                |1.1.2               |DONE      |Manifest: NOSIGNATURE
		IMBlocker_4.0.5+1.20.jar                          |IMBlocker                     |imblocker                     |4.0.5               |DONE      |Manifest: NOSIGNATURE
		fruitsdelight-1.0.11.jar                          |Fruits Delight                |fruitsdelight                 |1.0.11              |DONE      |Manifest: NOSIGNATURE
		domesticationinnovation-1.7.1-1.20.1.jar          |Domestication Innovation      |domesticationinnovation       |1.7.1               |DONE      |Manifest: NOSIGNATURE

### The latest.log file and hs_err_pidXXX if exists

<script src="https://gist.github.com/AQUAMEinGithub/920b1f827fc8467bc30373e9a21551df.js"></script>

### Issue description

After I summoned a red cap when using version 1.5.2, the game crashed immediately and the world could not be entered again. When I switched to version 1.4.9, I no longer encountered this problem. I also installed Oculus, but I don't know if that has any effect on this.

**Comment by ewewukek** [comment]
summoning red cap no longer crashes the game
