### ISSUE TITLE
conflict with epic fights

### ISSUE THREAD

**Issue by WoodsPrawn23** [ewewukek/mc-musketmod#47]
### Minecraft version

1.20.1

### Mod loader you are using

Forge

### Musket Mod version

forge 1.20.1

### Modpack info or mod list

Epic Fights and ewewukek's musket mod 
![image](https://github.com/user-attachments/assets/d1b2a0b9-1443-465d-809f-cf45f5b44f5d)

### The latest.log file and hs_err_pidXXX if exists

i dont know what that is 

### Issue description

crashes loading into game or in the first movement in the game 

### Steps to reproduce (if reproducing the issue requires exact steps)

config epic fights turn on filter animation load into game boom crash 
[crash-2024-10-01_05.21.59-client.txt](https://github.com/user-attachments/files/17203525/crash-2024-10-01_05.21.59-client.txt)

**Comment by ewewukek** [comment]
well, my mod no longer crashes the game but still incompatible with Epic Fight. not sure I'm going to try making it compatible. I'll put it in my todo list but no promise
