### ISSUE TITLE
Should make it into a datapack too

### ISSUE THREAD

**Issue by Kruseified** [ewewukek/mc-musketmod#48]
### Request information

😉

**Comment by ewewukek** [comment]
please elaborate

**Comment by Kruseified** [comment]
Create a data pack version of this resource, so as it can be integrated into a server/network

**Comment by ewewukek** [comment]
ah, I get it now. but this is source code of a mod. data packs rely on existing features but can't add new. or maybe repurpose existing in some clever way to add new mechanics.
also I've never tried to make a data pack. but if someone wants to, they can use my assets freely

**Comment by jwaxy** [comment]
you can create a [Polymer](https://modrinth.com/mod/polymer) variation of your mod so the clients wont need to install the mod
