### ISSUE TITLE
Feature Request: Offhand compatability

### ISSUE THREAD

**Issue by AzureMonument** [ewewukek/mc-musketmod#8]
The bow and crossbow can both be used in the offhand, why not the musket?

Thanks for the mod~♪

**Comment by ewewukek** [comment]
because holding two muskets in both hands and firing them both looked silly and op) but I can make musket usable from offhand if player doesn't have another musket in main hand. probably with some accuracy penalty

**Comment by ewewukek** [comment]
after some thought I decided to leave original behavior. mod now has pistols that can be used in the offhand. imo it makes more sense to hold sword & pistol than sword & musket.
